### ISSUE TITLE
Update Description

### ISSUE THREAD

**Issue by GnomiBerlin** [bb-Ricardo/fritzinfluxdb#102]
Hi, perhaps I have not seen it. 
Is there a clear discription, how tp update e.g. from 1.1.0 to 1.2.1 without overwriting the adapted e.g. ini files?
Thanks

**Comment by bb-Ricardo** [comment]
Hi,

well, there is no description.

But here are the options:
If you use the sources directly, a simple `git pull` will do the trick.
If you use docker-compose a `docker-compuse pull` and a `docker-compose up` should get you the update.

If you used the config file as described in the README then these won't get overwritten by any of the actions mentioned.

If unsusre, copy the ini config file to a save location, do the install process again and copy the config file back.

All of this should work just fine.

Hope that helps.

Cheers
Ricardo

**Comment by GnomiBerlin** [comment]
thanks @bb-Ricardo ,
I did a new installation with saving fritzinfluxdb.ini,  fritzinfluxdb.service and model.py
This is due to the Raspberry-Pi usage and the other user and group configuration (pi) the "7590 AX" usage and the mentioned basic config file.

for "sudo git clone https://github.com/yunity/fritzinfluxdb.git"  the directory /opt/fritzinfluxdb has to be removed first.

I think you can close the issue and perhaps make an update hint into the github description with these new install and saving hints. 

Greetings Joerg
