### ISSUE TITLE
FritzInfluxDB does not run as systemd service, only as a script

### ISSUE THREAD

**Issue by todrees1967** [bb-Ricardo/fritzinfluxdb#104]
Hi, I just installed latest version on my Ubuntu 22.04 LTS server with InfluxDB2 on the same server. Running the script with "sudo ./fritzinfluxdb.py" shows no error and I can see data being written in my InfluxDB. Fritz Box is 6591 from Vodafone (still with FW 7.29). Running the script with -v shows some messages in regard to 7.29. When installing as systemd service and starting the service I see this on the status:

(.venv) torsten@ghost:/opt/fritzinfluxdb$ sudo systemctl status fritzinfluxdb
● fritzinfluxdb.service - Fritz to InfluxDB daemon
     Loaded: loaded (/etc/systemd/system/fritzinfluxdb.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-06-26 20:18:57 UTC; 492ms ago
    Process: 152759 ExecStart=/opt/fritzinfluxdb/.venv/bin/python /opt/fritzinfluxdb/fritzinfluxdb.py -d (code=exited, status=1/FAILURE)
   Main PID: 152759 (code=exited, status=1/FAILURE)
        CPU: 66ms

What can I check?

Thanks and Regards,
Torsten

**Comment by todrees1967** [comment]
Im Syslog finde ich noch diesen Fehler:
Jun 27 06:30:48 ghost fritzinfluxdb[198548]: ModuleNotFoundError: No module named 'urllib3'

**Comment by todrees1967** [comment]
Problem solved. Was due to rights issue.

**Comment by bb-Ricardo** [comment]
Hi,

I'm glad you found the issue. Sorry for not getting back in time, was a busy day.

**Comment by justgigia** [comment]
I have the same problem, where did you adjust the rights to solve?

**Comment by todrees1967** [comment]
> I have the same problem, where did you adjust the rights to solve?

Sorry, this is too long ago, that I recall, what I had changed....
