### ISSUE TITLE
Readme contains dead link

### ISSUE THREAD

**Issue by burkart** [bb-Ricardo/fritzinfluxdb#109]
Instead of https://grafana.com/dashboards/713, it should be https://grafana.com/grafana/dashboards/713-fritz-box-router-status/

**Comment by Sk4lli** [comment]
> Instead of https://grafana.com/dashboards/713, it should be https://grafana.com/grafana/dashboards/713-fritz-box-router-status/

Both links seems to Work Just fine.

**Comment by burkart** [comment]
Indeed. Weird, I'm sure it didn't work when I reported it. Maybe the redirect failed at the time. Since the old URL is rewritten to the new one, it's best to change the URL anyway to prevent issues once the redirect goes down (again).

**Comment by bb-Ricardo** [comment]
fixed link in README of `next-release` branch
