### ISSUE TITLE
Unknown FritzBox link type 'Ethernet'

### ISSUE THREAD

**Issue by FlHinrichsen** [bb-Ricardo/fritzinfluxdb#110]
INFO: Unknown FritzBox link type 'Ethernet'. Please report this link type as issue to the github_project

**Comment by bb-Ricardo** [comment]
Hi, 

thank you for reporting it.

What type of FritzBox do you have? Do you run it in a special mode?

**Comment by FlHinrichsen** [comment]
I have a Fritz!Box 7580.
It is running behind a Fiber cable modem, so the WAN port (Ethernet) is used insted of the DSL port.

**Comment by bb-Ricardo** [comment]
thank you

**Comment by bb-Ricardo** [comment]
Hi,

I added the Ethernet link type. to the list of possible link types. Can you check again if it works now?

Thank you.
