### ISSUE TITLE
FritzOS version 7.57 not compatible

### ISSUE THREAD

**Issue by todrees1967** [bb-Ricardo/fritzinfluxdb#112]
My FritzBox Cable was updated to 7,57, now the script does not fetch all data and I am getting errors like:

FritzOS version 7.57 not compatible with supported versions for 'System logs': 7.29 - 7.38

among others.

Do I miss something?

**Comment by bb-Ricardo** [comment]
Hi, this is fine as there is another `System logs` for Fritz 7.39 and higher: https://github.com/bb-Ricardo/fritzinfluxdb/blob/186de65d3875bd76abaf897d26c64e61d353e502/fritzinfluxdb/classes/fritzbox/service_definitions/logs.py#L56-L59

**Comment by todrees1967** [comment]
OK, but why is the dashboard "Fritz!Box Router Status" empty? The other three ones with the logs, calls and home automatition are not empty.

**Comment by krikk** [comment]
i also run FritzOS version 7.57 and have no problem with the dashboard, everything working fine

**Comment by bb-Ricardo** [comment]
> OK, but why is the dashboard "Fritz!Box Router Status" empty? The other three ones with the logs, calls and home automatition are not empty.

I'm also running 7.57 and the dashboard seems to work fine for this version. Also the system logs are not part of this dashboard.

I would recommend:
Please try to reinstall the dashboard and see if this solves your issue.

If not then please open an issue regardig this error.

Thank you.
