### ISSUE TITLE
Dashboard is loading slow with big databases

### ISSUE THREAD

**Issue by ikorbln** [bb-Ricardo/fritzinfluxdb#113]
Hi,

After some runtime (some weeks) the dashboard is getting very slow when loading the data.
I have three boxes and three instances writing in there own databases in influxdb.

Two of the three dashboards loading fine in a second, the third loads up to 10 seconds.
The IO-Rate on the databas is high at this moment.

I noticed that thw "slow" databas is up to 150MB big, the "fast" ones are under 50MB.

The "slow" Box is the main-box with all the clients on it.
Is it possible to reduce the incomming data that will be recorded?
I think it is the many data-points that causes the load delay in grafana.

**Comment by bb-Ricardo** [comment]
Hi,

There are multiple things you could do.

* reduce the time frame to 6h for the dashboard
* shorten the retention time https://docs.influxdata.com/influxdb/v2/reference/internals/shards/
* increase the interval of the queries https://github.com/bb-Ricardo/fritzinfluxdb/blob/186de65d3875bd76abaf897d26c64e61d353e502/fritzinfluxdb-sample.ini#L112-L114

Hope this helps

Cheers
Ricardo

**Comment by bb-Ricardo** [comment]
Did this work? can we close this issue?

**Comment by bb-Ricardo** [comment]
closed due to no response
