### ISSUE TITLE
More than one Fritzbox?

### ISSUE THREAD

**Issue by Taddy81** [bb-Ricardo/fritzinfluxdb#116]
Hello,
thank you for your great project!

I have connected 2 Fritzboxes via Site2Site and Wireguard. I also get the data from the remote Fritzbox with a second DockerContainer.
But if the bucket is also stored as "Fritz.box", can I save 2 Fritz boxes in one bucket or do I have to use 2 buckets and therefore 2 dashboards?

LG

**Comment by bb-Ricardo** [comment]
Hi,

It's possible to just use the same bucket. Just define different `box_tag` values for each box and then you can select the box at the top the dashboard.

Let me know if this worked.

**Comment by Taddy81** [comment]
Is box_tag a Environment variables?

Try this, but InfluxDB shows only fritz.box, i also Change the Fritzbox Name

![Unbenannt](https://github.com/bb-Ricardo/fritzinfluxdb/assets/116562965/2eb0aa92-4fbe-44e5-a7c4-6853d6061409)

**Comment by bb-Ricardo** [comment]
It's a configuration option in the config file or an Environment variable if you use it as docker container

**Comment by Taddy81** [comment]
The Screenshot is from Portainer, i add BOX_NAME but this didnt work 
![Unbenannt](https://github.com/bb-Ricardo/fritzinfluxdb/assets/116562965/71942428-7acf-4b80-acb0-d4f588e66fa8)

**Comment by bb-Ricardo** [comment]
In this case the var name should be `FRITZBOX_BOX_TAG`

**Comment by Taddy81** [comment]
Thanks!!! That works!
