### ISSUE TITLE
expected RPAREN, got EOF error

### ISSUE THREAD

**Issue by fabbricalox** [bb-Ricardo/fritzinfluxdb#117]
Hi,
when using the "explore" functionality of grafana I get errors:
invalid: compilation failed: error @22:6-38:1: expected RPAREN, got EOF error @22:69-22:76: got unexpected token in string expression @22:75-22:76: ILLEGAL error @36:27-38:1: got unexpected token in string expression @38:1-38:1: EOF

This is from -> FRITZ!Box Router Status -> Overview -> Current UP/DOWN -> Explore

The graphs seem to work though.
Anyone knows what is happening here?

Influxdb2 2.7.1-1
prometheus 2.35.0-5

Thanks.

**Comment by bb-Ricardo** [comment]
Hi,

I never had that issue before.

You mentioned prometheus, is it used with fritzinfluxdb?

Which version of Grafana do you use?

**Comment by fabbricalox** [comment]
Hi,
sorry about confusion with prometheus; this is used for data in other dashboards.
The grafana version we use is
Grafana v10.0.2 (b2bbe10fbc)

To clarify:
The graphs look ok, the above "error"(?) appears only when clicking "explore":

**Comment by bb-Ricardo** [comment]
This seems to be an issue with the newer Grafana version. Will have to double check.

**Comment by bb-Ricardo** [comment]
which Grafana Version are you using? have you seen issue #123 ?
