### ISSUE TITLE
FRITZ!Box Router Status dashboard broken in Grafana v11.1.0

### ISSUE THREAD

**Issue by Aldjinn** [bb-Ricardo/fritzinfluxdb#123]
Hey,
I've been using your project for a long time now without any issues, many thanks for that.

But after upgrading my Grafana to v11.1.0, the FRITZ!Box Router Status dashboard seems to be broken. The other three ones are still working fine.

Grafana v10.4.5:
![Grafana-v10 4 5](https://github.com/bb-Ricardo/fritzinfluxdb/assets/1187929/8abd97fc-05d8-4cfd-8fac-3d5404b26717)

Grafana v11.1.0:
![Grafana-v11 1 0](https://github.com/bb-Ricardo/fritzinfluxdb/assets/1187929/91c2ce24-3f6b-4aec-a716-91f5c65327b5)

I'm not sure if the issue could related to this, because the other three still working dashboards show it as well.
![influxdb](https://github.com/bb-Ricardo/fritzinfluxdb/assets/1187929/586ca00f-59eb-443e-b00a-5ad491e6fbdb)

I've tested with Firefox 127.0.2 and Edge 126.0.2592.81, both show the same behavior.

**Comment by falke9176** [comment]
I see the difference. It may be that something has changed in the variables in Grafana that is also different from the other dashboards.

You cannot select the FritzBox - it only shows "None".

![image](https://github.com/bb-Ricardo/fritzinfluxdb/assets/154016371/b386c923-2c68-42c4-a0c2-9bf49a0896f0)

**Comment by Aldjinn** [comment]
That's correct, @falke9176. The FritzBox is not selectable.

**Comment by Aldjinn** [comment]
That's the query in the dashboard:

```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "$measurement" and r._field == "linkuptime")
  |> keyValues(keyColumns: ["box"])
  |> group()
  |> keep(columns: ["box"])
  |> distinct(column: "box")
```

**Comment by falke9176** [comment]
Something is wrong with getting the value for the variable `boxtag`

f.e. this is the JSON Code of Table "FritzBox Info":
```
from(bucket: v.defaultBucket)
  |> range(start: -1d)
  |> filter(fn: (r) => r._measurement == "${measurement}" and r.box == "${boxtag}" and
    (
      r._field == "external_ip" or
      r._field == "external_ipv6" or
      r._field == "ipv6_prefix" or
      r._field == "ipv6_prefix_length" or
      r._field == "model" or
      r._field == "serialnumber" or
      r._field == "softwareversion" or
      r._field == "last_auth_error" or
      r._field == "myfritz_host_name"
    ) 
  )
  |> last()
  |> toString()
  |> drop(columns: ["box", "_measurement", "_start", "_stop", "_time"])
  |> map(fn: (r) =>  ({
        r with _field:
          if r._field == "external_ip" then "IPv4"
          else if r._field == "external_ipv6" then "IPv6"
          else if r._field == "ipv6_prefix" then "IPv6 Prefix"
          else if r._field == "ipv6_prefix_length" then "IPv6 Prefix Length"
          else if r._field == "model" then "Model"
          else if r._field == "serialnumber" then "Serial"
          else if r._field == "softwareversion" then "SW Version"
          else if r._field == "last_auth_error" then "Last Auth Error"
          else if r._field == "myfritz_host_name" then "MyFritz Hostname"
          else r._field
        })
      )
```
and the Query Inspector of Grafana for that panel shows this:
```
from(bucket: "fritzbox")
  |> range(start: -1d)
  |> filter(fn: (r) => r._measurement == "fritzbox" and r.box == "" and
    (
      r._field == "external_ip" or
      r._field == "external_ipv6" or
      r._field == "ipv6_prefix" or
      r._field == "ipv6_prefix_length" or
      r._field == "model" or
      r._field == "serialnumber" or
      r._field == "softwareversion" or
      r._field == "last_auth_error" or
      r._field == "myfritz_host_name"
    ) 
  )
  |> last()
  |> toString()
  |> drop(columns: ["box", "_measurement", "_start", "_stop", "_time"])
  |> map(fn: (r) =>  ({
        r with _field:
          if r._field == "external_ip" then "IPv4"
          else if r._field == "external_ipv6" then "IPv6"
          else if r._field == "ipv6_prefix" then "IPv6 Prefix"
          else if r._field == "ipv6_prefix_length" then "IPv6 Prefix Length"
          else if r._field == "model" then "Model"
          else if r._field == "serialnumber" then "Serial"
          else if r._field == "softwareversion" then "SW Version"
          else if r._field == "last_auth_error" then "Last Auth Error"
          else if r._field == "myfritz_host_name" then "MyFritz Hostname"
          else r._field
        })
      )
```
So I changed the "boxtag" to the right Boxname-Value - and all tables of this dashboard are shown the results.

mmmhh I'm not so deep fit in Grafana .......

**Comment by bb-Ricardo** [comment]
Hi, Seems like Grafana broke the dashboard again. Have you tried reimporting it. This worked in the past.

**Comment by Aldjinn** [comment]
Yes, I already tried to reimport it. But unfortunately without success.

**Comment by stepman0** [comment]
In the other dashboards, "fritz.box" is also not shown, only the option "all":
![image](https://github.com/bb-Ricardo/fritzinfluxdb/assets/17684034/8394d97e-a49a-46d7-ad65-3b77fc1572a6)

I tried adding all to the variable in the FRITZ!Box Router Status dashboard, but no values are shown:
![image](https://github.com/bb-Ricardo/fritzinfluxdb/assets/17684034/8f6c3996-1a5d-4484-9e26-e0768000eb85)

**Comment by Real-Slice** [comment]
Hello all,
I had the same problem and found one working solution for me.
Open the FRITZ!Box Router Status Dashboard, go to Dashboard Settings, then Settings-Variables and edit the boxtag Variable.
Scroll down to Select Options and select Include All option and write in the field Custom all value: fritz.box
Then Run query and Apply
![custon all value](https://github.com/bb-Ricardo/fritzinfluxdb/assets/45244464/0cd72dee-bd01-4395-8c53-31be35c96729)
After this when you open the Dashboard again, it will automatically load it.

**Comment by bb-Ricardo** [comment]
I currently don't have access to an influxdb 2 instance. Can someone take the influx query for the variable and run it in the influxdb 2 UI? If it works there then Grafana might have an issue.

**Comment by joos2k** [comment]
I had the same problem after upgrading Grafana. This is a Grafana problem with InfluxDB. It was introduced in Grafana 11.1. A fix is ready, but I think a new version was not released yet.

https://github.com/grafana/grafana/issues/88983

**Comment by bb-Ricardo** [comment]
@joos2k, great finding, thank you.

I tried to upgrade to Grafana 11.1 and it wouldn't even show a login prompt anymore, so I had to downgrade to 10 again. 🤷‍♂️

**Comment by JF62** [comment]
There's a know bug in Grafana itself. Until it's fixed you can change the boxtag query by yourself to following:

from(bucket: v.defaultBucket)
  |> range(start: ${__from:date}, stop: ${__to:date})
  |> filter(fn: (r) => r._measurement == "$measurement" and r._field == "linkuptime")
  |> keyValues(keyColumns: ["box"])
  |> group()
  |> keep(columns: ["box"])
  |> distinct(column: "box")

**Comment by joos2k** [comment]
A fixed Grafana version has now been released. This problem no longer occurs for me with Grafana 11.1.1.

**Comment by Aldjinn** [comment]
Nice, I can confirm that the dashboard is running fine Grafana  with v11.1.1.

![grafik](https://github.com/user-attachments/assets/a37b709a-21a8-46ce-892e-a67f38d8cfdb)
![grafik](https://github.com/user-attachments/assets/702e48b4-fbba-4839-a83c-87a98f459373)

**Comment by bb-Ricardo** [comment]
Great. Thank you for reporting back.

Then Inwill close this issue.
