### ISSUE TITLE
Dashboard issues with System Information - Latest OS for FRITZ!Box 6591 Cable

### ISSUE THREAD

**Issue by Ashcora** [bb-Ricardo/fritzinfluxdb#124]
The versions before it was shown properly. Having the latest version installed for  FRITZ!Box 6591 Cable, the dashboard still shows data (like traffic overviews or log file entries) but the system status is throwing an error:
<img width="901" alt="2024-07-10_20h22_44" src="https://github.com/bb-Ricardo/fritzinfluxdb/assets/58374721/7de0c84d-66b7-4e65-956f-56a606d966e3">
<img width="906" alt="2024-07-10_20h24_18" src="https://github.com/bb-Ricardo/fritzinfluxdb/assets/58374721/00c0bf19-bc9c-4885-8530-6f949f20ae18">

The data is written correctly to InfluxDB:
<img width="874" alt="image" src="https://github.com/bb-Ricardo/fritzinfluxdb/assets/58374721/077014b1-c2f4-4111-bf77-503aa39f622b">

Extract from InfluxDB:

from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "${measurement}" and r["_field"] == "cpu_temp" and r.box == "${boxtag}")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> keep(columns: ["_value"])

Grafana is using this statement:

from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "${measurement}" and r["_field"] == "cpu_temp" and r.box == "${boxtag}")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> keep(columns: ["_value"])

--> In short: Identical statements.

It might be in best case somehow linked to the issue reported by @Aldjinn, see https://github.com/bb-Ricardo/fritzinfluxdb/issues/123
and/or the Grafana issue https://github.com/grafana/grafana/issues/88983 as mentioned by @joos2k

Currently using:
- Grafana v11.0.1 (302831c125)
- InfluxDB v2.7.6

**Comment by bb-Ricardo** [comment]
Hi,

What happens if you downgrade to Grafana 10?

**Comment by Ashcora** [comment]
Hi,

downgrading to e.g. Grafana v10.3.6 (186c34152a) makes no difference. The same charts are not loading :(

**Comment by bb-Ricardo** [comment]
ok. And deleting and reimporting the dashboard? Does this help in the downgraded version?

**Comment by bb-Ricardo** [comment]
Would close this one in favour of #123 as duplicate
