### ISSUE TITLE
Some Statistics are not working since FritzOS Update to 7.59 on Fritzbox 7530

### ISSUE THREAD

**Issue by netcruiser2k10** [bb-Ricardo/fritzinfluxdb#126]
My Fritzbox 7530 recently updated to a new FritzOs version 7.59 and since then the for the Daily Traffic Boxes on the Grafana Dashboard do not work and display nothing. I have done a git pull update and updated the pip libraries using pip3 install -r requirements.txt. Do you have any suggestions on how to fix this ?

**Comment by bb-Ricardo** [comment]
Hi @netcruiser2k10,

do you have any details on which data points are affected? Screenshot is also helpful.

Thank you.

**Comment by netcruiser2k10** [comment]
My Apologies for the late response, i have since migrated over to a new machine and thus created a whole fresh instance of this program which appears to be working as expeced. So im not sure what went wrong in the previous one.
