### ISSUE TITLE
No CPU, RAM, Temps and Hosts

### ISSUE THREAD

**Issue by Bond246** [bb-Ricardo/fritzinfluxdb#129]
Hello,

i'm using fritz2influx now for a while.
Migrating the container to different hosts, changing the complete hardware/docker-host and so on, never a problem.

But since some days i have no data for:
- cpu load
- ram load
- temperatures
- vpn users
- network hosts (passive and active)
- energy consuption

Before i upgraded to FritzOS 8.0 on my Fritzbox 7590 AX. But after that upgrade it worked for around 10 hours.
But i'm thinkig about if a docker-version upgrade to 27.3.1 could be the problem. 

The fritz2influx-Log looks ok to me
```
INFO: Starting main loop
INFO: Successfully connected to FritzBox '192.168.xxxx' (fritz.box) Model: FRITZ!Box 7590 AX (DSL) - FW: 8.0
INFO: Starting fritzinfluxdb v1.2.2 (2024-07-13)
INFO: Done reading config files
INFO: Successfully parsed config
INFO: Connection to InfluxDB v2.7.8 established and bucket is present
INFO: Successfully established FritzBox TR-069 session
INFO: Disabling queries via Lua. Fritz!OS version must be at least 7.XX
```

I'm using fritz2influx in a bridged docker-network. I've defined a custome bridge where also InfluxDBv2 is hosted.
Host is a ubuntu 24.04 on proxmox.

Any ideas why this metrics are not present anymore and how to fix it?

Thanks

**Comment by ronaldn1969** [comment]
The reason is, that your OS is 8.xx and not 7.xx

INFO: Disabling queries via Lua. Fritz!OS version must be at least 7.XX

Tom already made a modification... take a look her: https://github.com/bb-Ricardo/fritzinfluxdb/pull/128

**Comment by Bond246** [comment]
but it worked for about 10 hours after updating...?
ahhhhhhhhhh because of restarting the container it made a new version-test but with the running container it didn't noticed the change.
i will try this later... 

Thanks

**Comment by Bond246** [comment]
works 
Thanks again 👍

**Comment by bb-Ricardo** [comment]
Sorry, still being busy the last few days. Hope to add support asap.

**Comment by bb-Ricardo** [comment]
fixed in version https://github.com/bb-Ricardo/fritzinfluxdb/releases/tag/v1.2.3

**Comment by bb-Ricardo** [comment]
Oh wow, but not sure what I can do about it, if the FritzBox does not provide the values. Any ideas?

**Comment by bb-Ricardo** [comment]
So what is the current status? An error message appears on every start of the tool or on every request interval?

**Comment by bb-Ricardo** [comment]
Ah, famn it. Can you please post a json out for this one as well? Seems like a little f**k up by AVM.

**Comment by bb-Ricardo** [comment]
great, thank you for the quick response, I'll have a look.

**Comment by bb-Ricardo** [comment]
Hey @xyrolaith,

I just pushed a new commit to the `next-release` branch. can you please have a look?

thank you
