### ISSUE TITLE
AVM Smarthome Energy Consumption etc.?

### ISSUE THREAD

**Issue by 4920441** [bb-Ricardo/fritzinfluxdb#35]
Hi,

maybe I am overlooking the information here,

https://wiki.fhem.de/w/index.php?title=FRITZBOX

but isn't it possible to get informations about AVM's smarthome devices, such as energy-consumption, temperature etc. ?

Thanks a lot.

Cheers
4920441

**Comment by bb-Ricardo** [comment]
I would like to add these information to #33 but due to the lack of any Fritz Smart home devices I can't check how the data returned from the FritzBox looks like.

maybe you have a raspberry pi in your network which I could use to test.

**Comment by donnerhund** [comment]
Hi,

I am also very interested in logging the data from Dect200. Is there anything new here already?

**Comment by bb-Ricardo** [comment]
Due to the lack of such a device I'm unabl to implement support for it.

You can post the json reaponse from the FritzOS interface page where these values are displayed. Then I might be able to implement it.

**Comment by bb-Ricardo** [comment]
Same topic is discussed in #44. closing this as duplicate.
