### ISSUE TITLE
create_task() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by heugabel** [bb-Ricardo/fritzinfluxdb#39]
hi, how to fix this error?

Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]: /opt/fritzinfluxdb/fritzinfluxdb.py:141: RuntimeWarning: coroutine 'InfluxHandler.task_loop' was never awaited
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]:   task = loop.create_task(handler.task_loop(queue), name=handler.name)
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]: Traceback (most recent call last):
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]:   File "/opt/fritzinfluxdb/fritzinfluxdb.py", line 155, in <module>
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]:     main()
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]:   File "/opt/fritzinfluxdb/fritzinfluxdb.py", line 141, in main
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]:     task = loop.create_task(handler.task_loop(queue), name=handler.name)
Jul  2 01:11:09 raspberrypi fritzinfluxdb[21269]: TypeError: create_task() got an unexpected keyword argument 'name'

**Comment by donnerhund** [comment]
Have you already found a solution? I have exactly the same error message with my installation.

**Comment by bb-Ricardo** [comment]
Hi,

I don't really know why this is happening.

What kind of FritzBox Model are you using?

**Comment by donnerhund** [comment]
Hi,

I use the 7590.

**Comment by donnerhund** [comment]
Hi,

I have now carried out the installation again on another virtual machine. Now the programme runs without error message :)

**Comment by bb-Ricardo** [comment]
Ohhh, this might have something to do with the python version.

Which version was your "old" installation using?

**Comment by donnerhund** [comment]
Hi,
I completely forgot that an old Python version is still installed on the "old" installation.

python --version
Python 2.7.16

**Comment by bb-Ricardo** [comment]
Python 3.6 is the minimum requirement. That should be at the top of the README.

Maybe I should add an additional check for the python version used.

**Comment by bb-Ricardo** [comment]
Hi, I just pushed a fix to the next-release branch can you try this one? Thank you

**Comment by bb-Ricardo** [comment]
there is also `docker pull bbricardo/fritzinfluxdb:1.0.1-beta1` available
