### ISSUE TITLE
Syslog: ERROR: Unable to extract 'None' form....

### ISSUE THREAD

**Issue by donnerhund** [bb-Ricardo/fritzinfluxdb#42]
Hi,

I have a lot of entries like this in the syslog:

Jul 24 11:46:09 debian2 fritzinfluxdb[3289011]: ERROR: Unable to extract 'None' form '{'helplink': '/help/help.lua?sid=7edc2c0f4822faca&helppage=hilfe_syslog_752.html', 'time': '22:07:43', 'group': 'wlan', 'id': 752, 'msg': 'WLAN-Gerät hat sich abgemeldet (2,4 GHz), PC-B4-7C-9C-1B-7A-59, IP 192.168.1.100, MAC 14:2C:3C:4B:5A:69.', 'date': '13.07.22', 'nohelp': 0}', got '<class 'NoneType'>'
Jul 24 11:46:09 debian2 fritzinfluxdb[3289011]: ERROR: Unable to extract 'None' form '{'helplink': '/help/help.lua?sid=7edc2c0f4822faca&helppage=hilfe_syslog_756.html', 'time': '22:07:04', 'group': 'wlan', 'id': 756, 'msg': 'WLAN-Gerät hat sich neu angemeldet (2,4 GHz), 72 Mbit/s, PC-74-C2-46-E8-39-A4, IP 192.168.1.102, MAC 14:22:36:48:59:64.', 'date': '13.07.22', 'nohelp': 0}', got '<class 'NoneType'>'
Jul 24 11:46:09 debian2 fritzinfluxdb[3289011]: ERROR: Unable to extract 'None' form '{'helplink': '/help/help.lua?sid=7edc2c0f4822faca&helppage=hilfe_syslog_754.html', 'time': '22:07:02', 'group': 'wlan', 'id': 754, 'msg': 'WLAN-Gerät wurde abgemeldet (2,4 GHz), PC-74-C2-46-E8-39-A4, IP 192.168.1.102, MAC 11:22:36:48:49:54.', 'date': '13.07.22', 'nohelp': 0}', got '<class 'NoneType'>'

and

Jul 24 11:46:12 debian2 fritzinfluxdb[3289011]: ERROR: Unable to extract 'data.vpnInfo.server' form '{'pid': 'shareVpn', 'hide': {'ssoSet': True, 'shareUsb': True, 'mobile': True, 'liveTv': True, 'faxSet': True, 'provServ': True, 'boxExchange': True, 'rrd': True}, 'timeTillLogout': '1200', 'time': [], 'data': {'init': {'userConnections': {'connection1': {'connected': False, 'active': True, 'userId': '', 'deletable': True, 'address': '', 'type': 'homeNetworkVpn', 'psk': '', 'virtualAddress': '192.168.1.201', 'name': 'namexx'}, 'connection0': {'connected': False, 'active': True, 'userId': 'boxuser11', 'deletable': True, 'address': '', 'type': 'homeNetworkVpn', 'psk': 'ETcwUvaquZjqHome', 'virtualAddress': '192.168.1.200', 'name': 'vpn'}}, 'type': 'IPSec Xauth PSK', 'help': {'url': 'https://www.avm.de/service/vpn', 'text': 'www.avm.de/service/vpn'}, 'boxConnections': [], 'server': 'abc.firewall-gateway.com'}}, 'sid': '7edc2c0f4822faca'}', got '<class 'NoneType'>'
Jul 24 11:46:12 debian2 fritzinfluxdb[3289011]: ERROR: Unable to extract 'data.vpnInfo.type' form '{'pid': 'shareVpn', 'hide': {'ssoSet': True, 'shareUsb': True, 'mobile': True, 'liveTv': True, 'faxSet': True, 'provServ': True, 'boxExchange': True, 'rrd': True}, 'timeTillLogout': '1200', 'time': [], 'data': {'init': {'userConnections': {'connection1': {'connected': False, 'active': True, 'userId': '', 'deletable': True, 'address': '', 'type': 'homeNetworkVpn', 'psk': '', 'virtualAddress': '192.168.1.201', 'name': 'namexx'}, 'connection0': {'connected': False, 'active': True, 'userId': 'boxuser11', 'deletable': True, 'address': '', 'type': 'homeNetworkVpn', 'psk': 'ETcwUvaquZjqHome', 'virtualAddress': '192.168.1.200', 'name': 'vpn'}}, 'type': 'IPSec Xauth PSK', 'help': {'url': 'https://www.avm.de/service/vpn', 'text': 'www.avm.de/service/vpn'}, 'boxConnections': [], 'server': 'abc.firewall-gateway.com'}}, 'sid': '7edc2c0f4822faca'}', got '<class 'NoneType'>'
Jul 24 11:46:12 debian2 fritzinfluxdb[3289011]: ERROR: Unable to extract 'data.vpnInfo.userConnections' form '{'pid': 'shareVpn', 'hide': {'ssoSet': True, 'shareUsb': True, 'mobile': True, 'liveTv': True, 'faxSet': True, 'provServ': True, 'boxExchange': True, 'rrd': True}, 'timeTillLogout': '1200', 'time': [], 'data': {'init': {'userConnections': {'connection1': {'connected': False, 'active': True, 'userId': '', 'deletable': True, 'address': '', 'type': 'homeNetworkVpn', 'psk': '', 'virtualAddress': '192.168.1.201', 'namexx': 'namexx'}, 'connection0': {'connected': False, 'active': True, 'userId': 'boxuser11', 'deletable': True, 'address': '', 'type': 'homeNetworkVpn', 'psk': 'ETcwUvaquZjqHome', 'virtualAddress': '192.168.1.200', 'name': 'vpn'}}, 'type': 'IPSec Xauth PSK', 'help': {'url': 'https://www.avm.de/service/vpn', 'text': 'www.avm.de/service/vpn'}, 'boxConnections': [], 'server': 'abc.firewall-gateway.com'}}, 'sid': '7edc2c0f4822faca'}', got '<class 'NoneType'>'

Any idea what's wrong?

**Comment by bb-Ricardo** [comment]
Hi, which FritzBox and FritzOS version are you using?

**Comment by donnerhund** [comment]
Hi,
I use the Fritzbox 7590 with 07.39-97058 BETA

**Comment by bb-Ricardo** [comment]
Hi, good to know. I heaven't reated 7.39, only 7.29.

They Added WireGuard and probably changed the VPN output.

Will take care of it once I'm back.

**Comment by bb-Ricardo** [comment]
Hi, I just pushed some changes to the `next-release` branch. Can you test it please with 7.39 and see if it works now?

Thank you

**Comment by donnerhund** [comment]
Hi,
many thanks
When I start the programme with ./fritzinfluxdb.py, everything now works as desired. No error message appears in the syslog and the logs of the Fritzbox are displayed in Grafana.
But if I start the programme with sudo systemctl start fritzinfluxdb 
the following appears in the syslog:

Aug 21 12:33:19 vmdebian systemd[1]: Stopped Fritz to InfluxDB daemon.
Aug 21 12:33:19 vmdebian systemd[1]: Started Fritz to InfluxDB daemon.
Aug 21 12:33:19 vmdebian fritzinfluxdb[1516888]: Traceback (most recent call last):
Aug 21 12:33:19 vmdebian fritzinfluxdb[1516888]:   File "/opt/fritzinfluxdb/fritzinfluxdb.py", line 26, in <module>
Aug 21 12:33:19 vmdebian fritzinfluxdb[1516888]:     from fritzinfluxdb.classes.fritzbox.handler import FritzBoxHandler, FritzBoxLuaHandler
Aug 21 12:33:19 vmdebian fritzinfluxdb[1516888]:   File "/opt/fritzinfluxdb/fritzinfluxdb/classes/fritzbox/handler.py", line 10, in <module>
Aug 21 12:33:19 vmdebian fritzinfluxdb[1516888]:     import urllib3
Aug 21 12:33:19 vmdebian fritzinfluxdb[1516888]: ModuleNotFoundError: No module named 'urllib3'
Aug 21 12:33:19 vmdebian systemd[1]: fritzinfluxdb.service: Main process exited, code=exited, status=1/FAILURE
Aug 21 12:33:19 vmdebian systemd[1]: fritzinfluxdb.service: Failed with result 'exit-code'.


I know this is not a fritzinfluxdb problem, but maybe you have a tip for me.

dh@vmdebian:/usr/local$ pip3 show urllib3
Name: urllib3
Version: 1.26.5
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /usr/lib/python3/dist-packages
Requires:
Required-by: influxdb-client

many Thanks

**Comment by bb-Ricardo** [comment]
Hi, great to hear.

Did you follow the installation instructions? It is important that the virtual environment is greated. After that you need to activate it and then install the dependencies. Then it should work without any issues.

**Comment by donnerhund** [comment]
Hi,

I believe that I have followed all the steps in the documentation correctly.
This is what I have done:
cd /opt
sudo rm -r fritzinfluxdb
sudo git clone --branch next-release https://github.com/yunity/fritzinfluxdb.git
cd fritzinfluxdb
sudo virtualenv -p python3 .venv
. .venv/bin/activate
sudo pip3 install -r requirements.txt

**Comment by bb-Ricardo** [comment]
mmhm, looks good so far.

I close this issue as the original error seems to be solved. Can you please open a discussion and we can solve the issue there.

Thank you
