### ISSUE TITLE
Influx field type conflic

### ISSUE THREAD

**Issue by nixfindus** [bb-Ricardo/fritzinfluxdb#46]
Hi, I have the issue that the script is not working because an influx fiel type conflict:

{"error":"partial write: field type conflict: input field \"passive_hosts_name\" on measurement \"fritzbox\" is type integer, already exists as type string dropped=1"}

Is there any workaround to solve this?

Thanks a lot

**Comment by bb-Ricardo** [comment]
Good point I think I have to specifiy the precise type for the hosts fields. Will have a look.

**Comment by nixfindus** [comment]
I am grateful for your work

**Comment by bb-Ricardo** [comment]
Hi, I just pushed a fix to the next-release branch can you try this one? Thank you

**Comment by nixfindus** [comment]
I installed it quickly and at first glance everything looks very good.
I will now watch it and report back.
Thank you for the quick solution!
