### ISSUE TITLE
Failed to connect to InfluxDB: HTTPConnectionPool...

### ISSUE THREAD

**Issue by juko1711** [bb-Ricardo/fritzinfluxdb#55]
Hi Ricardo,
I've installed fritzinfluxdb on an Raspberry.
InfluxDB Version 1.8.0 is running on FreeBSD Jail, influxdb.hostname:port = http://192.168.178.39:8086.
**If I use:**
pi@RasPiTest1:/opt/fritzfluxdb $ curl -sl -I http://192.168.178.39:8086/ping
**I get**
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: aab2d99a-375f-11ed-8003-901b0ee7022b
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.0
X-Request-Id: aab2d99a-375f-11ed-8003-901b0ee7022b
Date: Sun, 18 Sep 2022 14:39:14 GMT
No issue as fare as I understand....
**If I run:**
sudo python3 ./fritzinfluxdb.py -d -v
**I get:**
INFO: Starting fritzinfluxdb v1.0.1 (2022-08-22)
INFO: Done reading config files
DEBUG: Config: influxdb.version = 1
DEBUG: Config: influxdb.hostname = http://192.168.178.39
DEBUG: Config: influxdb.port = 8086
DEBUG: Config: influxdb.tls_enabled = False
DEBUG: Config: influxdb.verify_tls = False
DEBUG: Config: influxdb.measurement_name = fritzbox
DEBUG: Config: influxdb.username = admin
DEBUG: Config: influxdb.password = adm***
DEBUG: Config: influxdb.database = MonitorTest
DEBUG: Config: influxdb.token = ***
DEBUG: Config: influxdb.organisation =
DEBUG: Config: influxdb.bucket =
DEBUG: Config: fritzbox.hostname = 192.168.178.1
DEBUG: Config: fritzbox.username = wikomon
DEBUG: Config: fritzbox.password = wik***
DEBUG: Config: fritzbox.port = 49000
DEBUG: Config: fritzbox.tls_enabled = False
DEBUG: Config: fritzbox.verify_tls = False
DEBUG: Config: fritzbox.connect_timeout = 10
DEBUG: Config: fritzbox.request_interval = 10
DEBUG: Config: fritzbox.box_tag = fritz.box
DEBUG: Config: fritzbox.timezone = Europe/Berlin
INFO: Successfully parsed config
**ERROR: Failed to connect to InfluxDB: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.178.39:8086/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75cd5448>: Failed to establish a new connection: [Errno -2] Name or service not known'))**
DEBUG: Initiating new FritzBox TR-069 session
INFO: Successfully established FritzBox TR-069 session
DEBUG: Initiating new FritzBox Lua session
INFO: Successfully established FritzBox Lua session
ERROR: Initializing connection to InfluxDB failed

With an simple Python script usin InfluxDBClient from influxdb lib I can connect to the InfluxDB and can read e.g. get_list_database....
Hope you have a hint for me.

Best regards

**Comment by bb-Ricardo** [comment]
Hi, what happens if you leave out the http protocol part and use:
```ini
hostname = 192.168.178.39
```
instead

**Comment by bb-Ricardo** [comment]
any updates?

**Comment by alafad** [comment]
Hello Ricardo, today i have tried to setup your Fritzbox monitoring, but i cant connect Grafana to my Influx.  Everytime i get an 401 Error, but i have created a custom Header "Authorization" with the Value "ZK9iIxxxxxxxxxxxxxxfdtQ==" and also tried "Token ZK9iIxxxxxxxxxxxxxxxfdtQ==".

I think the influxdb setup is correct, because I have some field like "active_hosts_mac" in my bucket. 

If I connect it with flux, it also works but the Dashboard doesnt understand this, for my opinion? (Is there a Dashboard for Flux?)

Thank you and greetings

**Comment by bb-Ricardo** [comment]
Hi,

It should work with `Token ZK9iIxxxxxxxxxxxxxxxfdtQ==`.

And yes, the current dashboard uses the older query language and is not compatible with Flux. For this to work I have to rewrite every query in the dashboard. And currently I just don't have enough time to do that.

**Comment by alafad** [comment]
> Hi,
> 
> It should work with `Token ZK9iIxxxxxxxxxxxxxxxfdtQ==`.
> 
> And yes, the current dashboard uses the older query language and is not compatible with Flux. For this to work I have to rewrite every query in the dashboard. And currently I just don't have enough time to do that.

Thank you for your answer, in the second try of all installations it works.

But now I have another problem :

How can I setup a grafana alert to get alerted if an update es avaible, I have probed a view things which expressions and the upgrade available field, but I have always the "no data" state..

Could you please help me or give me an example?

**Comment by ronaldn1969** [comment]
> 
> But now I have another problem :
> 
> How can I setup a grafana alert to get alerted if an update es avaible, I have probed a view things which expressions and the upgrade available field, but I have always the "no data" state..
> 
> Could you please help me or give me an example?

Hi... I think it's easier to get the information (FW update) directly from the box as e-mail notification.

**Comment by bb-Ricardo** [comment]
> > But now I have another problem :
> > How can I setup a grafana alert to get alerted if an update es avaible, I have probed a view things which expressions and the upgrade available field, but I have always the "no data" state..
> > Could you please help me or give me an example?
> 
> Hi... I never used Grafana alerts before, so I can't help in this mater, but I think it's easier to get the information (FW update) directly from the box as e-mail notification.

Hi, this is what I thought as well. Just add eMail notification and your FritzBox will let you know about any new available updates. It is under System -> Push Service

**Comment by alafad** [comment]
Thanks for your answers, but want to learn a little bit more about the grafana alerting, because i would transfer the knowledge of this alert to others prospective alerts.

**Comment by bb-Ricardo** [comment]
Sorry, I haven't used Grafana alerts at all so I won't be much help.

**Comment by bb-Ricardo** [comment]
I will close this issue for now as the "original" problem has been resolved
