### ISSUE TITLE
Migrate all dashboards to "flux" query language

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/fritzinfluxdb#63]
Once this is done, all dashboards shall be only using "flux" to query InfluxDB 1.8 and 2.0.

InfluxDB version <= 1.7.X won't be supported anymore.

**Comment by bb-Ricardo** [comment]
Hi, yes that is the goal as well. Half of it is done already and I just need to copy it, the rest should be not too difficult.

**Comment by bb-Ricardo** [comment]
Hey @ronaldn1969,

If you don't mind, you can try out the dashboards in here: [flux-dashboards](https://github.com/bb-Ricardo/fritzinfluxdb/tree/flux-dashboards)
All dashboards use Flux except for the system dashboard.

**Comment by ronaldn1969** [comment]
Hi Ricardo

Actually I try to get my TIG Docker running with InfluxDB v2. Not so easy. I don't want to start 4 containers every time. As soon as I have it running, I will switch and test it.

Oh... It might be possible to use fulx also on the 1.8? I will check later...

**Comment by bb-Ricardo** [comment]
Yes, you can also use the flux dashboards on a InfluxDB 1.8. There you have to set the Token to:
```
<username>:<password>
```

**Comment by bb-Ricardo** [comment]
This took way longer then I liked it to. But now we have all dashboards in flux language as well.

https://github.com/bb-Ricardo/fritzinfluxdb/tree/next-release/grafana/influx2_dashboards

InfluxDB 2.2 or newer is needed. Highly appreciating test and validation.
