### ISSUE TITLE
INFO: Requested invalid action 'GetInfo' for service: WANIPConnection:1

### ISSUE THREAD

**Issue by Missingmew** [bb-Ricardo/fritzinfluxdb#64]
Using a fritzbox 7490 with fritzOS 7.29

Recently came across this service after stumbling across fritzcollectd.

Managed to set it up just fine but a bunch of panels in the grafana dashboard end up empty.

The log notes the message in the title, followed by
```
INFO: Requested invalid action 'GetInfo' for service: WANIPConnection:1
INFO: Querying action 'GetInfo' will be disabled
INFO: All actions for service 'WANIPConnection:1' are unavailable. Disabling service.
```

After inspecting the dashboard further and checking the data that gets stored in the influxdb, it looks like the empty panels require data which would normally be fetched from the WANIPConnection interface, explaining why it doesnt show up.

I checked the XML that the box supplies manually and it does list a `GetInfo` for `WANIPConnection`.

Are there any known incompatibilities with the 7490 or 7.29?

**Comment by bb-Ricardo** [comment]
Hi,

I guess I have tonadd some information for these confusing log messages.

These are values only present when it is a Cable model. Should have nothing to do with your missing values.

You can use `-v` command line option to see which data is collected and sent to influxdb. You can check the query in the grafana panel (which seems to have data missing) for the name of the measurement. Now you can check the logs if the measurement is sent to influxdb. If so, then you can use an infludb query and see what it returns for this measurement.

Would be interested if data gets lost somewhere in this process.

**Comment by Missingmew** [comment]
Right after getting your response I rechecked grafana and a number of fields that didnt have values before now do (including the last 5 log entries).
However the large Current UP/DOWN graph still doesnt work.
I grabbed the query grafana produces and ran it by hand against the influxdb and it does return results. Running with `-v` also shows that there is indeed data fetched and stored by `fritzinfluxdb`, including the fields the query uses.
It appears like this is some kind of issue with grafana instead of the data collection, will investigate further...

**Comment by bb-Ricardo** [comment]
I'm currently in the process of moving the dashboards from influxQL to Flux language #63. You can try out the "next-release" branch for better support und bug fixes if you like.

**Comment by bb-Ricardo** [comment]
Hey @Missingmew,

this should now be fixed in `next-release`. The log message should be more explicit about it and the level got changed to DEBUG.

Also there are some issues with the dashboards in Grafana 9.2

You might want to give the dashboards here a try: https://github.com/bb-Ricardo/fritzinfluxdb/tree/next-release/grafana

**Comment by Missingmew** [comment]
The dashboards from `next-release` appear to have worked their magic, everything works now.
And since the original message had nothing to do with it Im happy, thanks a lot.
