### ISSUE TITLE
Error during Fritz OS update

### ISSUE THREAD

**Issue by dp20eic** [bb-Ricardo/fritzinfluxdb#67]
Hi,
I run my FritzBox with the beta version of AVM's FritzOS. There is a regular interruption in communication between "fritzinfluxdb" and the Fritzbox when a new update is started during the night, only restart the service helps.

From "fritzinfluxdb.ini:

```
# the maximum of time in seconds which a connection to the FritzBox is allowed to take
connect_timeout = 60

# interval to request data from FritzBox in seconds
# the value CAN'T be lower then 10 seconds
request_interval = 20
```

First lines from journaled log, attached the whole log file until I restart fritzinfluxdb:
```
Oct 29 01:52:22 loki fritzinfluxdb[91201]: ERROR: Unable to perform request to 'http://192.168.178.1/data.lua': HTTPConnectionPool(host='192.168.178.1', port=80): Read timed out. (read timeout=60)
Oct 29 01:52:22 loki fritzinfluxdb[91201]: ERROR: Unable to request FritzBox Lua service 'Passive network hosts', no data returned
Oct 29 01:53:07 loki fritzinfluxdb[91201]: ERROR: Unable to request FritzBox TR-069 data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Oct 29 01:53:07 loki fritzinfluxdb[91201]: ERROR: Unable to request FritzBox TR-069 data: HTTPConnectionPool(host='192.168.178.1', port=49000): Max retries exceeded with url: /upnp/control/wandslifconfig1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa8d9387b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

grep "ERROR" from journaled log only the last from 29.10.2022:
[journaled_error_fritzinfluxdb.log.gz](https://github.com/bb-Ricardo/fritzinfluxdb/files/9893250/journaled_error_fritzinfluxdb.log.gz)

ERROR from FritzBox:
```
Anmeldung an der Benutzeroberfläche von IP-Adresse [IP-Adresse] gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse [IP-Adresse] beendet.

```

**Comment by bb-Ricardo** [comment]
Hi,

I had this issue once as well and it should be fixed in the `next-release` branch.

commit: 489f2ac3c94a983d69f646ff76e591c7e6191cd6

Can you try this one and see if it works?

**Comment by dp20eic** [comment]
> Hi,
> 
> I had this issue once as well and it should be fixed in the `next-release` branch.
> 
> commit: [489f2ac](https://github.com/bb-Ricardo/fritzinfluxdb/commit/489f2ac3c94a983d69f646ff76e591c7e6191cd6)
> 
> Can you try this one and see if it works?

Hi,
I will give it a try, today evening.

with kind regards
Bernd

**Comment by dp20eic** [comment]
Hi,
I installed yesterday from "next-Release" and it runs without problems, so now I wait until AVM have a new beta 4 my box :)
I x the fingers, that it works :)

with kind regards
Bernd

**Comment by bb-Ricardo** [comment]
Hi,

just tested it with a simple restart from the UI and it worked now as it meant to be, established new session and continued as before: 
<img width="1390" alt="Bildschirmfoto 2022-11-01 um 21 13 29" src="https://user-images.githubusercontent.com/771836/199332013-2624b6af-677d-4e64-9e00-520d82832490.png">

**Comment by bb-Ricardo** [comment]
I consider this resolved. If you still see the same behaviour please report back and we can reopen the issue

**Comment by dp20eic** [comment]
Hi @bb-Ricardo,

my Fritz Box got a new OS Version, about the time of OS migration I got a lot of messages, but after this "fritzinfluxdb" starts again and has been running without problems since then :)

great job.

VG
Bernd


```
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetInfo' for service: LANHostConfigManagement
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetInfo' for service: WLANConfiguration:1
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetTotalAssociations' for service: WLANConfiguration:1
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetInfo' for service: WLANConfiguration:2
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetTotalAssociations' for service: WLANConfiguration:2
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetInfo' for service: WLANConfiguration:3
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetTotalAssociations' for service: WLANConfiguration:3
Nov 05 02:27:48 loki fritzinfluxdb[171580]: WARNING: Requested invalid action 'GetDDNSInfo' for service: X_AVM-DE_RemoteAccess
Nov 05 02:28:13 loki fritzinfluxdb[171580]: ERROR: Unable to request FritzBox Lua service 'Cable Info', no data returned
Nov 05 02:28:16 loki fritzinfluxdb[171580]: INFO: Successfully established FritzBox Lua session

```
