### ISSUE TITLE
linkuptime contains IP and DSL uptime

### ISSUE THREAD

**Issue by TwentyWasHere** [bb-Ricardo/fritzinfluxdb#72]
With a FritzBox 7950 (OS 7.29) as a data source I noticed that the field "linkuptime" contains increasing values both for IP and DSL in my InfluxDB2

Screenshot from the raw table from Grafana: https://prnt.sc/_eXt_OWGu3xy

The large integers are the DSL uptime the smaller ones the Internet uptime since the last IP address change. They are not alternating, and sometimes there are multiple IP or DSL uptimes in the table before the other shows up again.

These two uptimes should be in two different fields and not randomly written to the same.

**Comment by TwentyWasHere** [comment]
Looked at the code. Three times "linkuptime" in tr609.py

1x WANIPConn, which would be the DSL sync uptime in my case
1x WANPPPConnection, which would be the PPoE Uptime (so when the box got an IP)
1x WANIPConnection, IP uptime for cable

I just renamed the linkuptime to ip_linkuptime for DSL and Cable since only one is used on a given box and now the values are not mixed. Have not checked if connection_status/last_connection_error are handled similar.

**Comment by bb-Ricardo** [comment]
Hi, thank you for this issue.

Indeed this is not correct. I will have a look how to fix properly.

**Comment by TwentyWasHere** [comment]
This is how I fixed for me:
https://github.com/TwentyWasHere/fritzinfluxdb/commit/20da5396a9b3c429e16fd841c965d898acdde4c1

**Comment by bb-Ricardo** [comment]
Thank you for the change

**Comment by bb-Ricardo** [comment]
in current `next-release`
