### ISSUE TITLE
unable to retrive data from influxdb on grafana

### ISSUE THREAD

**Issue by bjtox** [bb-Ricardo/fritzinfluxdb#73]
Hi i've recreate a new fresch installation of stak but i can't get metrics from influxdb from grafana.
i've check on dashoard config variables: in "box" query there are no results.
i use InfluxDB v2.5.1 and grafana 9.1.8

thanks in advance

**Comment by bb-Ricardo** [comment]
Hey,

The config for your influxdb source in Grafana changed a bit.

- you need to add influx with Flux query language
- set the hostname and port
- set the organization, buket and token in the bottom part of the source configuration
- Then you need to use the new influx2 dashboards

Does this help?

**Comment by bjtox** [comment]
Thanks ricardo for reply, i understand the issue. i've load the wrond dashboard

**Comment by bb-Ricardo** [comment]
Does it now work for you?
Do you think the description in the README needs some improvements?

**Comment by bjtox** [comment]
thanks ricardo it's work now
no the readme was fine. i don't have read readme changes i've just see "next release merged in master" so i automatically update without read it
