### ISSUE TITLE
How to monitor multiple FBs?

### ISSUE THREAD

**Issue by littlezaphod** [bb-Ricardo/fritzinfluxdb#75]
Dear Ricardo,
just a question: I am running fritzinfluxdb inside docker. What would be the best solution to query more than one Fritzbox? Can it be done with a single fritzinfluxdb instance? Or should I duplicate the container and use a second .ini file?
Any hints appreciated!
best regards, Patric

**Comment by bb-Ricardo** [comment]
Hi,

Yes you would need tunrun a container for each FritzBox. Just have a look at the example docker-compose.yaml file.

**Comment by littlezaphod** [comment]
Thx, I will try and post my results

**Comment by littlezaphod** [comment]
I included 2 services in my docker compose file, they start 2 separate fritzinfluxdb cointainers whichstream their data to 2 influxdb (v2) buckets. Works great, again many thx for that awesome project of yours!

**Comment by bb-Ricardo** [comment]
Hi,

You can use the same bucket but have tonmake sure each box uses a different box tag. This way you can use the same dashboard and switch between the different boxes in the top peft corner.
