### ISSUE TITLE
influx2_dashboards/fritzbox_system_dashboard.json: several errors

### ISSUE THREAD

**Issue by pohly** [bb-Ricardo/fritzinfluxdb#84]
I recently reconfigured my InfluxDB source to use Flux and recreated the FritzBox dashboard from grafana/influx2_dashboards/fritzbox_system_dashboard.json in commit e38dc2abfba8600b5fea8ee9828b59ec611b2ba4.

I now get errors in some panels:
- `invalid: error @1:1-1:18: invalid import path timezone`, for example in "Last 24h Upload"
- `invalid: type error @3:30-3:34: record is missing label add`, for example in "Current Traffic"

Grafana v9.1.6, InfluxDB  2.0.9.

**Comment by bb-Ricardo** [comment]
Hi, unfortunately timezone support for "Flux" was only added with InfluxDB version 2.2.

Also See here:
https://github.com/bb-Ricardo/fritzinfluxdb/blob/main/README.md#grafana

You can:
a) update to recent version of InfluxDB or
b) configure a second source which uses the influxql language and use the Influx 1.8 dashboard (these are not maintained anymore)

**Comment by pohly** [comment]
Resolved by updating InfluxDB - thanks for the guidance. I should have RTFM... :grin:
