### ISSUE TITLE
Bandwith scale not dynamic

### ISSUE THREAD

**Issue by Ray-Hoo** [bb-Ricardo/fritzinfluxdb#85]
In the grafana influx 2 dashboard the scale for the DSL Speed is not dynamic. As the Internet speed is used in a variable way, it would be nice that the scale is reduced to what is really the maximum bandwidth within that time period instead of the maximum obtainable line speed as advertised in the Fritz Box..

**Comment by bb-Ricardo** [comment]
Hey @Ray-Hoo, 

you can easily adjust this yourself. Just edit the panel and change it as you please.
