### ISSUE TITLE
A few fields doesnt work (for me) since FritzOS 7.50

### ISSUE THREAD

**Issue by alafad** [bb-Ricardo/fritzinfluxdb#86]
Hello Ricardo, since my fritzos update (v7.50) i have a few fields which are no more covered.

Sample: 
![grafik](https://user-images.githubusercontent.com/95884402/209479363-69997b6d-1334-45e9-9d22-e20aa7dbfc7c.png)

I have updated to 1.1.0 few weeks ago, but it changes nothing.
Today i have updated to 1.20 and changed the Grafana Dashboard but i still have only 50 percentage og fields that works in Graphana.

I think this problem concerns only me, because a misconfiguration, I am right?

```

root@docker:~# docker logs fritzinfluxdb
2022-12-25 18:44:36,655 - INFO: Starting fritzinfluxdb v1.0.1 (2022-08-22)
2022-12-25 18:44:36,686 - INFO: Successfully parsed config
2022-12-25 18:44:36,703 - INFO: Connection to InfluxDB v2.4.0 established and bucket is present
2022-12-25 18:44:41,114 - INFO: Successfully established FritzBox TR-069 session
2022-12-25 18:44:43,085 - INFO: Successfully established FritzBox Lua session
2022-12-25 18:44:43,085 - INFO: Successfully connected to FritzBox '192.168.10.1' (fritz.box) Model: FRITZ!Box 7590 - FW: 7.50
2022-12-25 18:44:43,086 - INFO: Starting main loop
2022-12-25 18:44:43,811 - INFO: Requested invalid action 'GetInfo' for service: WANIPConnection:1
2022-12-25 18:44:43,811 - INFO: Querying action 'GetInfo' will be disabled
2022-12-25 18:44:43,811 - INFO: All actions for service 'WANIPConnection:1' are unavailable. Disabling service.
```

Could you please help me ?

**Comment by bb-Ricardo** [comment]
Hi @alafad,

according to the logs you are still running v1.0.1:
```
2022-12-25 18:44:36,655 - INFO: Starting fritzinfluxdb v1.0.1 (2022-08-22)
```

If you are running it with docker-compose try
```
docker-compose pull
docker-compose up -d
```

**Comment by alafad** [comment]
Thank you, such a silly mistake, i have forgot to pull the new container.

Now I ran into another problem, I cant establish a connection to my fritzbox 192.168.10.1

`root@docker:~/fritzinfluxdb-prod# docker-compose up
fritzinfluxdb is up-to-date
Attaching to fritzinfluxdb
fritzinfluxdb    | INFO: Starting fritzinfluxdb v1.2.0 (2022-12-23)
fritzinfluxdb    | INFO: Successfully parsed config
fritzinfluxdb    | INFO: Successfully create InfluxDB database mapping 'fritzinfluxdb-flux'
fritzinfluxdb    | INFO: Connection to InfluxDB v2.4.0 established and bucket is present
fritzinfluxdb    | Unable to get a connection: HTTPConnectionPool(host='192.168.178.1', port=49000): Max retries exceeded with url: /igddesc.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc395d74460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
fritzinfluxdb    | ERROR: Failed to connect to FritzBox via TR-069 'Unable to get a connection: HTTPConnectionPool(host='192.168.178.1', port=49000): Max retries exceeded with url: /igddesc.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc395d74460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))'
fritzinfluxdb    | INFO: Disabling queries via Lua. Fritz!OS version must be at least 7.XX
fritzinfluxdb    | ERROR: Initializing connection to FritzBox TR-069 failed
fritzinfluxdb    | INFO: Starting fritzinfluxdb v1.2.0 (2022-12-23)
fritzinfluxdb    | INFO: Successfully parsed config
fritzinfluxdb    | INFO: Connection to InfluxDB v2.4.0 established and bucket is present
fritzinfluxdb    | Unable to get a connection: HTTPConnectionPool(host='192.168.178.1', port=49000): Max retries exceeded with url: /igddesc.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b1616be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))gre`

I have changed all false IPs which i found with 

`root@docker:~/fritzinfluxdb-prod# grep -r 192.168.178.1 .
`
But the problem still exists, where could the IP hardcoded ?

**Comment by bb-Ricardo** [comment]
You can either use the config file:
https://github.com/bb-Ricardo/fritzinfluxdb/blob/main/fritzinfluxdb-sample.ini#L86

Or set the environment variable https://github.com/bb-Ricardo/fritzinfluxdb#environment-variables:
`FRITZBOX_HOSTNAME`

**Comment by alafad** [comment]
Thanks, now it works!

**Comment by bb-Ricardo** [comment]
Hey, just wondering if the problem is fixed now.
