### ISSUE TITLE
Permit connection to Influxdb without user and password

### ISSUE THREAD

**Issue by RREE** [bb-Ricardo/fritzinfluxdb#88]
My Influxdb V1 is set up without authentication. I can successfully start your script if I remove `username` and `password` from the mandatory_keys in `fritzinfluxdb/classes/influxdb/config.py`.

**Comment by bb-Ricardo** [comment]
should be possible to implement

**Comment by bb-Ricardo** [comment]
Hi, I just pushed a new commit to `next-release` branch. Can you test it and see if it works?

thank you.
