### ISSUE TITLE
INFO: Service 'DSL Info not applicable for this FritzBox Model Link type 'Cable'

### ISSUE THREAD

**Issue by Ashcora** [bb-Ricardo/fritzinfluxdb#92]
The current version seems to have an issue with "Cable" models.
_INFO: Service 'DSL Info (Fritz!OS 7.29 - latest)' not applicable for this FritzBox Model Link type 'Cable'_

Extract from log file:

INFO: Successfully established FritzBox TR-069 session
INFO: Successfully established FritzBox Lua session
INFO: Successfully connected to FritzBox '192.168.1.1' (fritz.box) Model: FRITZ!Box 6591 Cable (Cable) - FW: 7.39
INFO: Starting main loop
INFO: Service 'DSL Info (Fritz!OS 7.29 - latest)' not applicable for this FritzBox Model Link type 'Cable'

**Comment by ronaldn1969** [comment]
@Ashcora 

Hi Tobias

No... Everything is fine... You have cable access and therefore it's not possible to get DSL info.

I have DSL access and didn't get cable info

Cheers
Ronald


```
 INFO: Successfully established FritzBox TR-069 session
 INFO: Successfully established FritzBox Lua session
 INFO: Successfully connected to FritzBox '192.168.178.1' (fritz.box) Model: FRITZ!Box 7590 (DSL) - FW: 7.50
 INFO: Starting main loop
 INFO: Service 'Cable Info (Fritz!OS 7.29 - latest)' not applicable for this FritzBox Model Link type 'DSL'
```

**Comment by Ashcora** [comment]
@ronaldn1969: Should the script not recognize the version (DSL or Cable) of the Fritzbox? This information might be misleading, especially as the information provided in line 3 is not correct regarding the model and the firmware (currently it is 7.39 beta)

**Comment by ronaldn1969** [comment]
IMHO the script is doing this. In my case it's DSL, FB 7590 and v 7.50... You don't have a 6591 Cable?
