### ISSUE TITLE
2 minor issues found that need to be fixed!

### ISSUE THREAD

**Issue by jimpapi** [bb-Ricardo/fritzinfluxdb#97]
1) the external ip address that grafana dashboard shows is wrong.
i also checked the fritzinfluxdb database and also there the external_ip written is wrong. Probably the python files need to  be updated
![grafana ip](https://user-images.githubusercontent.com/96443559/220832575-8150afe0-6b7d-43d7-9f22-483ab190266d.jpg)
![fritzbox ip](https://user-images.githubusercontent.com/96443559/220832642-14b6d02a-105b-4b5d-8d1d-905cd5680531.jpg)

2) the other problem might be a dashboard problem.
the download or upload speed bandwidth is wrong if the dashboard selected time interval is the past 12h or 24h or more than 12h anyway. It is right if the interval is the last 6 hours or less
![right bandwidth](https://user-images.githubusercontent.com/96443559/220833676-3c2cdf52-e24a-4616-a538-39bfdd655121.jpg)
![wrong bandwidth](https://user-images.githubusercontent.com/96443559/220833693-8883f4dc-7bf9-4065-a80e-1a3e98132c5c.jpg)

**Comment by bb-Ricardo** [comment]
Hi, thank you for the issue report.

I see the issue with 1) and might have something to do with carrier grade NAT. Can you run the script in DEBUG log level and send me the output from start until all the data is sent to influxdb?

The 2. issue is not really an issue.

This is the way how grafana limits the amount of datapoints displayed per panel.

A bigger timeframe increases the inaccuracy of the displayed data, especially for short peaks.

This is (afaik) a default behavior and can only be changed with a massive trade off in performance, displaying the data.

Cheers
Ricardo

**Comment by jimpapi** [comment]
Thank you for the quick responce...i will send it to you soon...

**Comment by bb-Ricardo** [comment]
Hey, just wondering if the issue still persists. Otherwise I would close this issue.

**Comment by jimpapi** [comment]
Hello! I have done 1router restart and again…the Ip is different in grafana

**Comment by bb-Ricardo** [comment]
Would you be able to provide the logs if you run it with log level DEBUG?

**Comment by jimpapi** [comment]
The logs from fritz!box?Στάλθηκε από το iPhone μου8 Μαρ 2023, 10:20 μμ, ο χρήστης «Ricardo ***@***.***>» έγραψε:﻿
Would you be able to provide the logs if you run it with log level DEBUG?

**Comment by bb-Ricardo** [comment]
Hi, no I meant the logs from the fritzinfluxdb script with option `-v`

**Comment by burkart** [comment]
To elaborate on item 2 from the original report regarding different values depending on the graph's time range: If the database holds one measurement every 10 seconds, that amounts to 8640 measurements over 24 hours. This is impossible to display precisely on all but the highest resolution screens anyway, however, all that data has to be transferred between InfluxDB and Grafana. It improves performance to combine multiple values at the database level and transfer only those aggregates, say one value every minute for 1440 values over a 24-hour period. Grafana can automatically pick a sensible interval depending on the graph width in pixels and its time range by using `$__interval` in an InfluxQL query like `SELECT mean(...) FROM ... WHERE $timeFilter GROUP BY time($__interval) fill(...)`.

InfluxDB will then calculate the mean (i. e., average) over each interval. The longer the graph's time range, the more raw values get averaged into one transferred aggregate value, so peaks get "ironed out". If one is particularly interested in the peaks, these can be shown regardless of graph width and time range by replacing `mean()` with `max()` in the query.

Personally, I find an average over a defined, long-ish interval like an hour or a day quite useful whereas I look more for the peaks in a "show as much detail as the graph width allows" type of graph. Then again, if the time range gets so long that the troughs between the peaks get lost, I would prefer the average. Depending on the data, this may only apply to time ranges spanning several months plus. Most universal, of course, is showing both.

**Comment by bb-Ricardo** [comment]
Would anyone be able to provide logs which is behind a carrier grade NAT in oder to be able to Find and extract the correct external IP address?

**Comment by bb-Ricardo** [comment]
closing this due to no response.
