### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by nouse4it** [bb-Ricardo/fritzinfluxdb#98]
Everytime i try to run the script fritzinfluxdb.py it breaks with the following error message:

`Traceback (most recent call last):
  File "/opt/fritzinfluxdb/./fritzinfluxdb.py", line 24, in <module>
    from fritzinfluxdb.cli_parser import parse_command_line
  File "/opt/fritzinfluxdb/fritzinfluxdb.py", line 24, in <module>
    from fritzinfluxdb.cli_parser import parse_command_line
ModuleNotFoundError: No module named 'fritzinfluxdb.cli_parser'; 'fritzinfluxdb' is not a package`

**Comment by bb-Ricardo** [comment]
Hi,

It seems you just copied the script by itself and not the whole repository.

Is that possible?

**Comment by nouse4it** [comment]
Hi,

no, I think that should be the complete repo.

`drwxr-xr-x 9 root root 4,0K  3. Mär 15:23 .
drwxr-xr-x 7 root root 4,0K 24. Aug 2022  ..
drwxr-xr-x 4 root root 4,0K  3. Mär 15:23 classes
-rw-r--r-- 1 root root 2,4K  3. Mär 15:23 cli_parser.py
-rw-r--r-- 1 root root 3,3K  3. Mär 15:23 common.py
-rw-r--r-- 1 root root 2,1K  3. Mär 15:23 configparser.py
-rw-r--r-- 1 root root  418  3. Mär 15:08 Dockerfile
drwxr-xr-x 3 root root 4,0K  3. Mär 15:08 fritzinfluxdb
-rw-r--r-- 1 root root 3,4K  3. Mär 15:14 fritzinfluxdb.ini
-rwxr-xr-x 1 root root 5,2K  3. Mär 15:08 fritzinfluxdb.py
-rw-r--r-- 1 root root 3,3K  3. Mär 15:08 fritzinfluxdb-sample.ini
drwxr-xr-x 8 root root 4,0K  3. Mär 15:08 .git
-rw-r--r-- 1 root root   52 21. Aug 2022  .gitignore
drwxr-xr-x 4 root root 4,0K  3. Mär 15:08 grafana
-rw-r--r-- 1 root root 1,1K  3. Mär 15:08 LICENSE.txt
-rw-r--r-- 1 root root 2,2K  3. Mär 15:23 log.py
-rwxr-xr-x 1 root root 1,3K  3. Mär 15:08 .publi.sh
drwxr-xr-x 2 root root 4,0K  3. Mär 15:14 __pycache__
-rw-r--r-- 1 root root 8,4K  3. Mär 15:08 README.md
-rw-r--r-- 1 root root   81  3. Mär 15:08 requirements.txt
drwxr-xr-x 2 root root 4,0K  3. Mär 15:08 test
drwxr-xr-x 4 root root 4,0K 21. Aug 2022  .venv`

**Comment by bb-Ricardo** [comment]
Mhh,

Something must went wrong here.

The files `cli_parser.py` or `common.py` should not be there.

Can you clone the whole repo again and then try again?

**Comment by nouse4it** [comment]
Hi,
it seems like there went something wrong when pulling the repo via git.
I now copied the file via my desktop and transfered the data via winscp.
Now it´s working.
Thank you for your help!

**Comment by bb-Ricardo** [comment]
Indeed, strange. Will close the ticket for now.
